name: gestion_commandes_client
description: Client Dart pour le système de gestion de commandes

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.5
  args: ^2.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0